#!/usr/bin/env node
/**
 * Fetch TypeScript types from Supabase
 *
 * Usage: npm run update-types
 */

import { execSync } from 'child_process';
import { writeFileSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = join(__dirname, '..', 'src', 'lib', 'database.types.ts');

// Extract project ID from PUBLIC_SUPABASE_URL in .env
function getProjectId() {
  try {
    const envPath = join(__dirname, '..', '.env');
    const envContent = readFileSync(envPath, 'utf-8');
    const match = envContent.match(/PUBLIC_SUPABASE_URL=https:\/\/([^.]+)\.supabase\.co/);
    if (match) return match[1];
  } catch {}
  return null;
}

const projectId = getProjectId();
if (!projectId) {
  console.error('❌ Could not find project ID in .env (PUBLIC_SUPABASE_URL)');
  process.exit(1);
}

console.log(`🔄 Generating TypeScript types from project: ${projectId}...`);

try {
  const types = execSync(`npx supabase gen types typescript --project-id ${projectId}`, {
    encoding: 'utf-8',
    cwd: join(__dirname, '..'),
  });

  const header = `// Auto-generated by Supabase CLI
// Run: npm run update-types
// DO NOT EDIT MANUALLY

`;

  writeFileSync(outputPath, header + types);
  console.log(`✅ Types written to ${outputPath}`);
} catch (error) {
  console.error('❌ Failed to generate types:', error.message);
  console.error('\nMake sure you are logged in: npx supabase login');
  process.exit(1);
}
